routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::Routes();
Route::group(['middleware' => 'auth'],function (){
    Route::post('/metas', 'MetasController@create')->name('crear');
    Route::get('/meta/objetivo/{id}','ObjetivosController@objetivo')->name('objetivos');
    Route::get('/', 'HomeController@index')->middleware('verified');
    Route::resource('metas', 'MetasController');
    Route::resource('estrategias', 'EstrategiasController');
    Route::resource('objetivos', 'ObjetivosController');
    Route::resource('reportes', 'ReportesController');
    Route::resource('users', 'UserController');
    Route::resource('perfils', 'PerfilController');
    Route::get('/estrategias/finalizo/{id}', 'EstrategiasController@finalizo')->name('finalizo');
    Route::post('descarga', 'ReportesController@export')->name('descargaexcel');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Desarrollador: Luis Fernando Jonathan Vargas Osornio - vojohn95@gmail.com">
    <meta name="author" content="Desarrollador: Victor Rojas Barrera - victorrb1015@gmail.com">
    <meta name="Version" content="produccion">
    <title>@yield('title' , 'Central')</title>
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>

</head>
<style>
    body {
        padding: 20px 20px;
    }

    .results tr[visible='false'],
    .no-result {
        display: none;
    }

    .results tr[visible='true'] {
        display: table-row;
    }

    .counter {
        padding: 8px;
        color: white;
    }
</style>

@guest
    @include('layouts.nav.nav')
@else
    @include('layouts.nav.nav_rh')
@endguest


<body style="padding-top: 90px;">
<main class="py-4">
    <div class="container">

        @yield('content')

    </div>
</main>
</body>
<footer class="page-footer font-small aqua-gradient  fixed-bottom">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© <?php echo date("Y"); ?> Copyright:
        <a href="https:central-mx.com" target="_blank"> Operadora Central de Estacionamientos SAPI de C.V.</a>
    </div>
    <!-- Copyright -->

</footer>

<link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('css/mdb.min.css') }}" rel="stylesheet">
<link href="{{ asset('css/style.css') }}" rel="stylesheet">
<link rel="icon" href="{{asset('logo/logo/login-logo.png')}}"/>
<link href="{{ asset('css/fullcalendar.min.css') }}" rel="stylesheet">
<link href="{{ asset('css/fullcalendar.print.min.css') }}" rel="stylesheet" media='print'/>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" ></script>
<!--<script type="text/javascript">
    //script para mensajes falsh
    $(window).load(function () {
        $(".loader").fadeOut("slow");
    });
</script>-->
<script>
    $('div.alert').not('.alert-important').delay(7000).fadeOut(1000);
</script>
@stack('maps')
<script type="text/javascript" src="{{asset('js/popper.min.js')}}" ></script>
<script type="text/javascript" src="{{asset('js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('js/mdb.min.js')}}" ></script>
<script type="text/javascript" src="{{asset('js/moment.min.js')}}" ></script>
<script type="text/javascript" src="{{asset('js/fullcalendar.min.js')}}" defer="defer"></script>
<script type="text/javascript" src="{{asset('js/lazysizes.min.js')}}" async="" ></script>

<!--Tabla con busqueda-->
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".search").keyup(function () {
            var searchTerm = $(".search").val();
            var listItem = $('.results tbody').children('tr');
            var searchSplit = searchTerm.replace(/ /g, "'):containsi('")
            $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
                    return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
                }
            });
            $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function(e){
                $(this).attr('visible','false');
            });
            $(".results tbody tr:containsi('" + searchSplit + "')").each(function(e){
                $(this).attr('visible','true');
            });

            var jobCount = $('.results tbody tr[visible="true"]').length;
            $('.counter').text(jobCount + ' item');

            if(jobCount == '0') {$('.no-result').show();}
            else {$('.no-result').hide();}
        });
    });
</script>
<script>
    @stack('scripts')
</script>


</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/errors.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('metas*') ? 'active' : '' }}">
    <a href="{{ route('metas.index') }}"><i class="fa fa-edit"></i><span>Metas</span></a>
</li>

<li class="{{ Request::is('estrategias*') ? 'active' : '' }}">
    <a href="{{ route('estrategias.index') }}"><i class="fa fa-edit"></i><span>Estrategias</span></a>
</li>

<li class="{{ Request::is('objetivos*') ? 'active' : '' }}">
    <a href="{{ route('objetivos.index') }}"><i class="fa fa-edit"></i><span>Objetivos</span></a>
</li>

<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{{ route('users.index') }}"><i class="fa fa-edit"></i><span>Users</span></a>
</li>

<li class="{{ Request::is('perfils*') ? 'active' : '' }}">
    <a href="{{ route('perfils.index') }}"><i class="fa fa-edit"></i><span>Perfils</span></a>
</li>

<li class="{{ Request::is('objetvisos*') ? 'active' : '' }}">
    <a href="{{ route('objetvisos.index') }}"><i class="fa fa-edit"></i><span>Objetvisos</span></a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>